num= input()
def fun ():
    print (str(a)+"*" + str(1) +"="  +str (a*1))
    print (str(a)+"*" + str(2) +"="  +str (a*2)) 
    print (str(a)+"*" + str(3) +"="  +str (a*3)) 
    print (str(a)+"*" + str(4) +"="  +str (a*4)) 
    print (str(a)+"*" + str(5) +"="  +str (a*5))
    print (str(a)+"*" + str(6) +"="  +str (a*6))
    print (str(a)+"*" + str(7) +"="  +str (a*7))
    print (str(a)+"*" + str(8) +"="  +str (a*8))
    print (str(a)+"*" + str(9) +"="  +str (a*9))
    print (str(a)+"*" + str(10) +"="  +str (a*10))

a = int(num[0])
print(a)    
fun()
a = int(num[1])
fun()
a = int(num[2])
fun()
a = int(num[3])
fun()
a = int(num[4])
fun()
a = int(num[5])
fun()
a = int(num[6])
fun()
a = int(num[7])
fun()
a = int(num[8])
fun()
a = int(num[9])
fun()
